import { useEffect,useState } from "react";
import { apiRequest } from "../lib/api";
import AdminLayout from "../components/AdminLayout";

export default function AdminFactorsPage(){

const [factors,setFactors] = useState<any>({});
const [saving,setSaving] = useState(false);

const fieldMeta: Record<string,{label:string;help:string;unit?:string}> = {
streaming_per_hour: {
  label: "Streaming Emission per Hour",
  help: "Estimated CO2 emission generated by one hour of streaming activity.",
  unit: "g CO2 / hour"
},
storage_per_gb: {
  label: "Storage Emission per GB",
  help: "Estimated CO2 associated with storing 1 GB of data.",
  unit: "g CO2 / GB"
},
cloud_per_gb_year: {
  label: "Cloud Emission per GB per Year",
  help: "Estimated annual CO2 impact of storing 1 GB in cloud systems.",
  unit: "g CO2 / GB / year"
},
download_per_gb: {
  label: "Download Emission per GB",
  help: "Estimated CO2 emitted per GB downloaded.",
  unit: "g CO2 / GB"
},
download_wifi_per_gb: {
  label: "Download Emission (Wi-Fi) per GB",
  help: "Estimated CO2 emitted per GB downloaded over Wi-Fi.",
  unit: "g CO2 / GB"
},
download_mobile_per_gb: {
  label: "Download Emission (Mobile Data) per GB",
  help: "Estimated CO2 emitted per GB downloaded over mobile data.",
  unit: "g CO2 / GB"
},
tiktok_per_min: {
  label: "TikTok Emission per Minute",
  help: "Estimated CO2 impact of one minute spent on TikTok.",
  unit: "g CO2 / min"
},
instagram_per_min: {
  label: "Instagram Emission per Minute",
  help: "Estimated CO2 impact of one minute spent on Instagram.",
  unit: "g CO2 / min"
},
facebook_per_min: {
  label: "Facebook Emission per Minute",
  help: "Estimated CO2 impact of one minute spent on Facebook.",
  unit: "g CO2 / min"
},
youtube_scroll_per_min: {
  label: "YouTube Emission per Minute",
  help: "Estimated CO2 impact of one minute spent browsing or streaming YouTube.",
  unit: "g CO2 / min"
},
email_per_unit: {
  label: "Email Emission per Email",
  help: "Estimated CO2 emitted per email action.",
  unit: "g CO2 / email"
},
email_per: {
  label: "Email Emission Factor",
  help: "General emission factor used for email related calculations."
},
text_per_unit: {
  label: "Text Message Emission per Message",
  help: "Estimated CO2 emitted per text message action.",
  unit: "g CO2 / text"
},
text_per: {
  label: "Text Message Emission Factor",
  help: "General emission factor used for text message calculations."
}
};

useEffect(()=>{
load();
},[]);


async function load(){

const data = await apiRequest("/api/admin/factors");

setFactors(data || {});

}


function update(key:string,value:any){

setFactors({
...factors,
[key]:Number(value)
});

}


async function save(){
setSaving(true);
try{

const res = await apiRequest("/api/admin/factors","POST",factors);
if(!res?.success){
alert("Update failed");
return;
}

alert("Factors updated");
}catch(err){
console.error(err);
alert("Update failed");
}finally{
setSaving(false);
}

}


return(

<AdminLayout>
<div className="max-w-7xl mx-auto">

<h1 className="text-2xl md:text-3xl font-bold mb-2">
CO₂ Factor Configuration
</h1>
<p className="text-gray-600 mb-6">
Update calculation constants used across baseline, weekly tracking, and analytics.
</p>

<div className="bg-white p-6 md:p-8 rounded-2xl shadow-sm border border-gray-100">

<div className="grid grid-cols-1 md:grid-cols-2 gap-5">
{Object.keys(factors).sort().map((key)=>{
const meta = fieldMeta[key];

return(

<div key={key} className="mb-4">

<label className="block text-sm font-semibold text-gray-800 mb-1">
{meta?.label || key.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase())}
</label>

<input
type="number"
step="any"
value={factors[key]}
onChange={(e)=>update(key,e.target.value)}
className="input"
/>
<p className="help">
{meta?.help || "Configuration factor used in impact calculations."}
{meta?.unit ? ` (${meta.unit})` : ""}
</p>

</div>

);

})}
</div>

<button
onClick={save}
disabled={saving}
className="bg-[#064e3b] hover:bg-[#053d2f] transition text-white px-6 py-2.5 mt-4 rounded-xl disabled:bg-gray-400"
>
{saving ? "Saving..." : "Save Factors"}
</button>

</div>

</div>
</AdminLayout>

);

}